// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhXnZrGXaowN7bnJH10q5o56GXi9LRNh4',
    appId: '1:454738184550:web:5c26f2420d0043c1a3e0a7',
    messagingSenderId: '454738184550',
    projectId: 'amorin-63a9f',
    authDomain: 'amorin-63a9f.firebaseapp.com',
    storageBucket: 'amorin-63a9f.firebasestorage.app',
    measurementId: 'G-37SE4J3TES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39tMd1-LXgjDYyy1pCjKYIFx-xMpLl6o',
    appId: '1:454738184550:android:691f8542ecba8e0fa3e0a7',
    messagingSenderId: '454738184550',
    projectId: 'amorin-63a9f',
    storageBucket: 'amorin-63a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfzEoTDCflBYBIIo2VuoprC60qx0I-ApY',
    appId: '1:454738184550:ios:c626dd947629414aa3e0a7',
    messagingSenderId: '454738184550',
    projectId: 'amorin-63a9f',
    storageBucket: 'amorin-63a9f.firebasestorage.app',
    iosBundleId: 'com.example.amorin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfzEoTDCflBYBIIo2VuoprC60qx0I-ApY',
    appId: '1:454738184550:ios:c626dd947629414aa3e0a7',
    messagingSenderId: '454738184550',
    projectId: 'amorin-63a9f',
    storageBucket: 'amorin-63a9f.firebasestorage.app',
    iosBundleId: 'com.example.amorin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhXnZrGXaowN7bnJH10q5o56GXi9LRNh4',
    appId: '1:454738184550:web:b64d529b6986e91da3e0a7',
    messagingSenderId: '454738184550',
    projectId: 'amorin-63a9f',
    authDomain: 'amorin-63a9f.firebaseapp.com',
    storageBucket: 'amorin-63a9f.firebasestorage.app',
    measurementId: 'G-GENXRRV0LM',
  );

}